using System.Collections;
using Code.Scripts.EventSystems;
using Singleton;
using UnityEngine;
using TMPro;
using UnityEngine.UI;
using DG.Tweening;
using Buildings;

public enum TutorialState
{
    NotStarted,
    CrashLandIntro,         // Story dialogue, instructions to toggle to building mode
    PoweringUpIDT,          // Wait for player to place Miner + Conveyors and feed 5 Coal
    IDTOnlineStoreLocked,   // IDT online, alert player to open the store (requisition defenses)
    RequisitionDefenses,    // Wait for player to buy ammo/turret/wall
    CombatRaidInitiated,    // Spawn 2 raiders, require firing and dodge roll
    Completed
}

public class TutorialManager : SingletonBase<TutorialManager>
{
    [Header("Dialogue Assets (Autogenerated if null)")]
    public DialogueSO introDialogue;
    public DialogueSO combatDialogue;
    private DialogueSO idtOnlineDialogue;

    [Header("State (ReadOnly)")]
    public TutorialState currentState = TutorialState.NotStarted;
    [SerializeField] private int currentDialogueIndex = -1;
    [SerializeField] private int coalFedCount = 0;
    [SerializeField] private bool hasFiredWeapon = false;
    [SerializeField] private bool hasDodgeRolled = false;
    private bool isSubscribed = false;

    protected override void Awake()
    {
        persistBetweenScenes = false;
        base.Awake();
    }

    private void Start()
    {
        bool playTutorial = PlayerPrefs.GetInt("PlayTutorial", 1) == 1;
        if (!playTutorial)
        {
            currentState = TutorialState.Completed;
            if (DayNightManager.Instance != null)
            {
                DayNightManager.Instance.isTutorialActive = false;
            }
            return;
        }

        InitializeDialogues();
        SubscribeEvents();
        StartCoroutine(StartTutorialRoutine());
    }

    private void InitializeDialogues()
    {
        // 1. Crash Land Intro Dialogue
        string[] introTexts = new string[]
        {
            "SYSTEM // INCOMING TRANSMISSION\n\nCRITICAL ERROR: Outpost ship hull breached. Crash-landed in sector Earth-99. Planetary atmospheric shield: OFFLINE.",
            "SYSTEM // INCOMING TRANSMISSION\n\nInterdimensional Transport (IDT) Safe Mode: ACTIVE. Transceiver link: OFFLINE. Primary reactor battery: depleted.",
            "OPERATIVE TRANSMISSION\n\nRequisition store is locked. You must route raw carbon (Coal) into the IDT input port to reboot systems and establish link.",
            "OPERATIVE TRANSMISSION\n\nSwitch to [BUILDING MODE] (Press Tab) to show your hotbar, select your Miner (rotate with R), and place Conveyor belts to route Coal into the IDT."
        };
        DialogueType[] introTypes = new DialogueType[]
        {
            DialogueType.None,
            DialogueType.None,
            DialogueType.Announcer,
            DialogueType.Announcer
        };
        introDialogue = CreateDialogueSO(introTexts, introTypes);

        // 2. IDT Online & Store Locked Dialogue
        string[] onlineTexts = new string[]
        {
            "SYSTEM // INCOMING TRANSMISSION\n\nReboot successful. Transceiver online. Satellite telemetry established. Account credited: +$100.",
            "OPERATIVE TRANSMISSION\n\nALERT: Active local scanning has exposed our position. Native human combatants are closing in.",
            "OPERATIVE TRANSMISSION\n\nRequisition database unlocked. Access the Company Catalog (Press E) to purchase defense equipment."
        };
        DialogueType[] onlineTypes = new DialogueType[]
        {
            DialogueType.None,
            DialogueType.Announcer,
            DialogueType.Announcer
        };
        idtOnlineDialogue = CreateDialogueSO(onlineTexts, onlineTypes);

        // 3. Combat Raid Dialogue
        string[] combatTexts = new string[]
        {
            "OPERATIVE TRANSMISSION\n\nOutpost breach imminent. Equip standard arms. Switch to [COMBAT MODE] (Press Tab) to hide hotbar and activate target tracking.",
            "OPERATIVE TRANSMISSION\n\nAim with Mouse, shoot with Left Click, and Dodge-Roll (Space/Dodge key) to avoid incoming fire. Protect the IDT!"
        };
        DialogueType[] combatTypes = new DialogueType[]
        {
            DialogueType.Announcer,
            DialogueType.Announcer
        };
        combatDialogue = CreateDialogueSO(combatTexts, combatTypes);
    }

    private DialogueSO CreateDialogueSO(string[] texts, DialogueType[] types)
    {
        DialogueSO so = ScriptableObject.CreateInstance<DialogueSO>();
        so.dialogues = new Dialogue[texts.Length];
        for (int i = 0; i < texts.Length; i++)
        {
            so.dialogues[i] = new Dialogue
            {
                text = texts[i],
                sprite = null,
                color = Color.clear,
                type = i < types.Length ? types[i] : DialogueType.None
            };
        }
        return so;
    }

    private void SubscribeEvents()
    {
        if (isSubscribed) return;
        isSubscribed = true;

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.OnDialogueEnded += HandleDialogueEnded;
            DialogueManager.Instance.CanAdvanceDialogue = CheckCanAdvanceDialogue;
        }

        PlayerWeapon.OnPlayerShoot += HandlePlayerShoot;
        
        if (PlayerController.Instance != null)
        {
            PlayerController.Instance.OnPlayerDodge += HandlePlayerDodge;
        }
    }

    private void UnsubscribeEvents()
    {
        if (!isSubscribed) return;
        isSubscribed = false;

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.OnDialogueEnded -= HandleDialogueEnded;
            DialogueManager.Instance.CanAdvanceDialogue = null;
        }

        PlayerWeapon.OnPlayerShoot -= HandlePlayerShoot;

        if (PlayerController.Instance != null)
        {
            PlayerController.Instance.OnPlayerDodge -= HandlePlayerDodge;
        }

        if (Seller.Instance != null)
        {
            Seller.Instance.OnFuelAdded -= HandleFuelAdded;
        }
    }

    protected override void OnDestroy()
    {
        base.OnDestroy();
        UnsubscribeEvents();
    }

    private IEnumerator StartTutorialRoutine()
    {
        yield return new WaitForSeconds(1.5f); // Let scene settle
        
        if (DayNightManager.Instance != null)
        {
            DayNightManager.Instance.isTutorialActive = true;
        }

        // Grant starting miner and conveyors
        GrantStartingItems();

        currentState = TutorialState.CrashLandIntro;
        PlayDialogue(introDialogue);
    }

    private void GrantStartingItems()
    {
        if (GameManager.Instance == null || GameManager.Instance.allBuildings == null) return;

        BuildingData minerData = null;
        BuildingData conveyorData = null;

        foreach (var b in GameManager.Instance.allBuildings)
        {
            if (b == null) continue;
            if (b.type == BuildingType.Miner) minerData = b;
            else if (b.type == BuildingType.Conveyor) conveyorData = b;
        }

        if (InventoryManager.Instance != null)
        {
            if (minerData != null) InventoryManager.Instance.AddBuilding(minerData, 1);
            if (conveyorData != null) InventoryManager.Instance.AddBuilding(conveyorData, 8);
        }
    }

    public bool IsStoreLocked()
    {
        return currentState == TutorialState.CrashLandIntro || currentState == TutorialState.PoweringUpIDT;
    }

    private void Update()
    {
        if (currentState == TutorialState.Completed) return;

        if (DialogueManager.Instance != null && DialogueManager.Instance.IsDialogueActive)
        {
            currentDialogueIndex = DialogueManager.Instance.currentDialogueIndex;
        }

        // Handle dynamic dialogue position
        bool isStoreOpen = UiManager.Instance != null && UiManager.Instance.StorePanel != null && UiManager.Instance.StorePanel.activeSelf;
        DialoguePositionMode targetMode = DialoguePositionMode.DefaultBottom;

        if (isStoreOpen)
        {
            targetMode = DialoguePositionMode.ShopLeftTop;
        }
        else if (currentState == TutorialState.CrashLandIntro && currentDialogueIndex >= 2)
        {
            targetMode = DialoguePositionMode.AboveHotbar;
        }
        else if (currentState == TutorialState.PoweringUpIDT)
        {
            targetMode = DialoguePositionMode.PlacementTop;
        }

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.SetPositionMode(targetMode);
        }

        // Core Tutorial State Transitions
        switch (currentState)
        {
            case TutorialState.CrashLandIntro:
                // Check if they toggled to Building mode
                if (PlayerController.Instance != null && PlayerController.Instance.currentMode == PlayerController.PlayerMode.Building)
                {
                    if (currentDialogueIndex == 3 && DialogueManager.Instance != null)
                    {
                        // Allow them to advance or auto-advance
                        AdvanceToDialogueIndex(3); // refresh display
                        currentState = TutorialState.PoweringUpIDT;
                        
                        // Close dialogue box to let them build, show HUD prompt
                        DialogueManager.Instance.ToggleUi(false);

                        // Subscribe to IDT fueling
                        if (Seller.Instance != null)
                        {
                            Seller.Instance.OnFuelAdded += HandleFuelAdded;
                        }

                        if (UiManager.HasInstance)
                        {
                            UiManager.Instance.ShowGeneralAlert("IDT OUT OF FUEL: COAL REQUIRED", new Color(1f, 0.5f, 0f));
                        }
                    }
                }
                break;

            case TutorialState.PoweringUpIDT:
                // Wait for fuel. Handled via HandleFuelAdded.
                break;

            case TutorialState.IDTOnlineStoreLocked:
                // Wait for store to open
                if (isStoreOpen)
                {
                    currentState = TutorialState.RequisitionDefenses;
                    if (DialogueManager.Instance != null)
                    {
                        DialogueManager.Instance.ToggleUi(false);
                    }
                }
                break;

            case TutorialState.RequisitionDefenses:
                // Wait until they buy ammo, wall, or turret AND close store
                bool hasBoughtDefense = GetInventoryCount(BuildingType.Turret) > 0 || 
                                       GetInventoryCount(BuildingType.Wall) > 0 || 
                                       (PlayerController.Instance != null && PlayerController.Instance.ammoReserve > 90);
                
                if (hasBoughtDefense && !isStoreOpen)
                {
                    currentState = TutorialState.CombatRaidInitiated;
                    
                    if (PlayerController.Instance != null)
                    {
                        PlayerController.Instance.canDodgeRoll = true; // Unlock dodge roll for tutorial
                    }

                    if (RaidManager.Instance != null)
                    {
                        RaidManager.Instance.StartCustomRaid(1, 2, 12f);
                    }

                    PlayDialogue(combatDialogue);
                }
                break;

            case TutorialState.CombatRaidInitiated:
                // Wait until they shot, dodge-rolled, and raid is repelled
                bool raidDefeated = RaidManager.Instance != null && !RaidManager.Instance.isRaidActive;
                int enemyCount = 0;
                if (GameManager.Instance != null && GameManager.Instance.ActiveEnemies != null)
                {
                    enemyCount = GameManager.Instance.ActiveEnemies.Count;
                }

                if (hasFiredWeapon && hasDodgeRolled && raidDefeated && enemyCount == 0)
                {
                    currentState = TutorialState.Completed;
                    CompleteTutorial(true);
                }
                break;
        }
    }

    private void PlayDialogue(DialogueSO dialogue)
    {
        if (dialogue == null) return;
        var eSet = new DialogueEvent { enabled = true, dialogue = dialogue, index = 0 };
        EventManager.Instance.Publish(eSet);
    }

    private bool CheckCanAdvanceDialogue()
    {
        if (DialogueManager.Instance == null) return true;
        int index = DialogueManager.Instance.currentDialogueIndex;

        if (currentState == TutorialState.CrashLandIntro && index == 3)
        {
            if (PlayerController.Instance != null && PlayerController.Instance.currentMode != PlayerController.PlayerMode.Building)
            {
                if (UiManager.HasInstance)
                {
                    UiManager.Instance.ShowGeneralAlert("PRESS TAB TO SWITCH TO BUILDING MODE", new Color(1f, 0.5f, 0f));
                }
                return false; // Block until building mode is active
            }
        }

        if (currentState == TutorialState.IDTOnlineStoreLocked && index == 2)
        {
            bool isStoreOpen = UiManager.Instance != null && UiManager.Instance.StorePanel != null && UiManager.Instance.StorePanel.activeSelf;
            if (!isStoreOpen)
            {
                if (UiManager.HasInstance)
                {
                    UiManager.Instance.ShowGeneralAlert("PRESS E TO OPEN COMPANY STORE", new Color(0.3f, 0.9f, 0.3f));
                }
                return false; // Block until store opens
            }
        }

        if (currentState == TutorialState.CombatRaidInitiated && index == 1)
        {
            if (!hasFiredWeapon || !hasDodgeRolled)
            {
                if (UiManager.HasInstance)
                {
                    string msg = !hasFiredWeapon ? "LEFT CLICK TO SHOOT" : "PRESS SPACE TO DODGE-ROLL";
                    UiManager.Instance.ShowGeneralAlert(msg, new Color(1f, 0.3f, 0.3f));
                }
                return false; // Block until they try controls
            }
        }

        return true;
    }

    private void AdvanceToDialogueIndex(int targetIndex)
    {
        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.currentDialogueIndex = targetIndex;
            var method = typeof(DialogueManager).GetMethod("SetDialogue", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            if (method != null) method.Invoke(DialogueManager.Instance, null);
            
            var coroutineMethod = typeof(DialogueManager).GetMethod("DialogueCoroutine", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            if (coroutineMethod != null)
            {
                var coroutine = (IEnumerator)coroutineMethod.Invoke(DialogueManager.Instance, null);
                var coroutineField = typeof(DialogueManager).GetField("_currentCoroutine", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                if (coroutineField != null)
                {
                    Coroutine current = (Coroutine)coroutineField.GetValue(DialogueManager.Instance);
                    if (current != null) DialogueManager.Instance.StopCoroutine(current);
                    
                    Coroutine newCoroutine = DialogueManager.Instance.StartCoroutine(coroutine);
                    coroutineField.SetValue(DialogueManager.Instance, newCoroutine);
                }
            }
        }
    }

    private void HandleDialogueEnded()
    {
    }

    private void HandleFuelAdded(ResourceType type)
    {
        if (currentState == TutorialState.PoweringUpIDT && type == ResourceType.Coal)
        {
            coalFedCount++;
            if (coalFedCount >= 5)
            {
                if (Seller.Instance != null)
                {
                    Seller.Instance.OnFuelAdded -= HandleFuelAdded;
                }

                // Reboot IDT!
                currentState = TutorialState.IDTOnlineStoreLocked;
                
                if (UiManager.HasInstance)
                {
                    UiManager.Instance.ShowGeneralAlert("IDT ONLINE - COMMUNICATIONS LINK ONLINE", new Color(0.2f, 1f, 0.2f));
                }

                if (CurrencyManager.Instance != null)
                {
                    CurrencyManager.Instance.AddCurrency(100f); // Startup grant
                }

                PlayDialogue(idtOnlineDialogue);
            }
        }
    }

    private void HandlePlayerShoot()
    {
        if (currentState == TutorialState.CombatRaidInitiated)
        {
            hasFiredWeapon = true;
        }
    }

    private void HandlePlayerDodge()
    {
        if (currentState == TutorialState.CombatRaidInitiated)
        {
            hasDodgeRolled = true;
        }
    }

    private int GetInventoryCount(BuildingType type)
    {
        if (InventoryManager.Instance == null || InventoryManager.Instance.items == null) return 0;
        var item = InventoryManager.Instance.items.Find(i => i.data != null && i.data.type == type);
        return item != null ? item.count : 0;
    }

    public void CompleteTutorial(bool showVisual)
    {
        currentState = TutorialState.Completed;

        if (showVisual)
        {
            ShowCompletionVisual();
        }

        PlayerPrefs.SetInt("PlayTutorial", 0);
        PlayerPrefs.Save();

        UnsubscribeEvents();

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.ToggleUi(false);
        }

        if (DayNightManager.Instance != null)
        {
            DayNightManager.Instance.CompleteTutorial();
            if (showVisual)
            {
                DayNightManager.Instance.timeRemaining = 10f; // Give them a few seconds before next day starts
            }
            else
            {
                DayNightManager.Instance.isTutorialActive = false;
            }
        }
    }

    public void RestartTutorial()
    {
        StopAllCoroutines();

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.ToggleUi(false);
        }

        currentState = TutorialState.CrashLandIntro;
        currentDialogueIndex = -1;
        coalFedCount = 0;
        hasFiredWeapon = false;
        hasDodgeRolled = false;
        // Reset states

        PlayerPrefs.SetInt("PlayTutorial", 1);
        PlayerPrefs.Save();

        if (DayNightManager.Instance != null)
        {
            DayNightManager.Instance.isTutorialActive = true;
        }

        SubscribeEvents();
        StartCoroutine(StartTutorialRoutine());
    }

    public static void RequestTutorialAgain()
    {
        PlayerPrefs.SetInt("PlayTutorial", 1);
        PlayerPrefs.Save();
        Debug.Log("Tutorial requested. It will play again on next scene start.");
    }

    private void ShowCompletionVisual()
    {
        GameObject canvasGo = GameObject.Find("HUD Canvas");
        if (canvasGo == null) canvasGo = GameObject.Find("Canvas");
        if (canvasGo == null) canvasGo = FindFirstObjectByType<Canvas>()?.gameObject;

        if (canvasGo == null) return;

        GameObject visualPanel = new GameObject("TutorialCompletionVisual", typeof(RectTransform), typeof(CanvasGroup));
        visualPanel.transform.SetParent(canvasGo.transform, false);

        RectTransform panelRt = visualPanel.GetComponent<RectTransform>();
        panelRt.anchorMin = new Vector2(0.5f, 0.5f);
        panelRt.anchorMax = new Vector2(0.5f, 0.5f);
        panelRt.pivot = new Vector2(0.5f, 0.5f);
        panelRt.anchoredPosition = new Vector2(0f, 100f);
        panelRt.sizeDelta = new Vector2(600f, 150f);

        CanvasGroup cg = visualPanel.GetComponent<CanvasGroup>();
        cg.alpha = 0f;

        GameObject bgGo = new GameObject("Background", typeof(RectTransform), typeof(Image));
        bgGo.transform.SetParent(visualPanel.transform, false);
        RectTransform bgRt = bgGo.GetComponent<RectTransform>();
        bgRt.anchorMin = Vector2.zero;
        bgRt.anchorMax = Vector2.one;
        bgRt.offsetMin = Vector2.zero;
        bgRt.offsetMax = Vector2.zero;
        Image bgImg = bgGo.GetComponent<Image>();
        bgImg.color = new Color(0f, 0.05f, 0f, 0.9f);
        Outline outline = bgGo.AddComponent<Outline>();
        outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.8f);
        outline.effectDistance = new Vector2(2f, -2f);

        GameObject textGo = new GameObject("Text", typeof(RectTransform), typeof(TextMeshProUGUI));
        textGo.transform.SetParent(visualPanel.transform, false);
        RectTransform textRt = textGo.GetComponent<RectTransform>();
        textRt.anchorMin = Vector2.zero;
        textRt.anchorMax = Vector2.one;
        textRt.offsetMin = new Vector2(10f, 10f);
        textRt.offsetMax = new Vector2(-10f, -10f);

        TextMeshProUGUI txt = textGo.GetComponent<TextMeshProUGUI>();
        txt.fontSize = 36;
        txt.fontStyle = FontStyles.Bold;
        txt.color = new Color(0.2f, 0.9f, 0.2f, 1f);
        txt.alignment = TextAlignmentOptions.Center;
        txt.text = "<color=#32FF32>TUTORIAL COMPLETED</color>\nSYSTEMS UNLOCKED\n<color=#FF3232>WARNING: RAID DETECTED</color>";

        Sequence seq = DOTween.Sequence();
        seq.Append(cg.DOFade(1f, 0.5f))
           .AppendInterval(0.2f)
           .AppendCallback(() => {
               outline.effectColor = new Color(1f, 0.2f, 0.2f, 0.9f);
           })
           .AppendInterval(0.3f)
           .AppendCallback(() => {
               outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.8f);
           })
           .AppendInterval(0.3f)
           .AppendCallback(() => {
               outline.effectColor = new Color(1f, 0.2f, 0.2f, 0.9f);
           })
           .AppendInterval(0.3f)
           .AppendCallback(() => {
               outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.8f);
           })
           .AppendInterval(2.5f)
           .Append(panelRt.DOAnchorPosY(150f, 0.8f).SetEase(Ease.InBack))
           .Join(cg.DOFade(0f, 0.8f))
           .AppendCallback(() => {
               Destroy(visualPanel);
           });

        seq.SetUpdate(true);
    }
}
