using System.Collections;
using Code.Scripts.EventSystems;
using Singleton;
using UnityEngine;
using TMPro;
using UnityEngine.UI;
using DG.Tweening;
using Buildings;

public enum TutorialState
{
    NotStarted,
    CrashLandIntro,         // Story dialogue, instructions to toggle to building mode
    PoweringUpIDT,          // Wait for player to place Miner + Conveyors and feed 5 Coal
    IDTOnlineStoreLocked,   // IDT online, alert player to open the store (requisition defenses)
    RequisitionDefenses,    // Wait for player to buy ammo/turret/wall
    CombatRaidInitiated,    // Spawn 2 raiders, require firing and dodge roll
    Completed
}

public class TutorialManager : SingletonBase<TutorialManager>
{
    [Header("Dialogue Assets (Autogenerated if null)")]
    public DialogueSO introDialogue;
    public DialogueSO combatDialogue;
    private DialogueSO idtOnlineDialogue;

    [Header("State (ReadOnly)")]
    public TutorialState currentState = TutorialState.NotStarted;
    [SerializeField] private int currentDialogueIndex = -1;
    [SerializeField] private int coalFedCount = 0;
    [SerializeField] private bool hasFiredWeapon = false;
    [SerializeField] private bool hasDodgeRolled = false;
    private bool isSubscribed = false;

    [Header("Objective UI")]
    private GameObject objectivePanel;
    private TMP_Text objectiveText;

    protected override void Awake()
    {
        persistBetweenScenes = false;
        base.Awake();
    }

    private void Start()
    {
        bool playTutorial = PlayerPrefs.GetInt("PlayTutorial", 1) == 1;
        if (!playTutorial)
        {
            currentState = TutorialState.Completed;
            if (DayNightManager.Instance != null)
            {
                DayNightManager.Instance.isTutorialActive = false;
            }
            return;
        }

        // InitializeDialogues(); // Bypassed: we are using objective HUD instead
        SubscribeEvents();
        StartCoroutine(StartTutorialRoutine());
    }

    private void InitializeDialogues()
    {
        // 1. Crash Land Intro Dialogue
        string[] introTexts = new string[]
        {
            "SYSTEM // INCOMING TRANSMISSION\n\nWARNING: Orbital extraction vessel hull breach. Crash-landed in hostile sector Earth-99. Atmospheric shields: DESTROYED.",
            "SYSTEM // INCOMING TRANSMISSION\n\nInterdimensional Transceiver link: OFFLINE. Corporate database link severed. Instant tech delivery catalog: LOCKED.",
            "OPERATIVE TRANSMISSION\n\nOperative, this is Company Command. Telemetry confirms your crash. The IDT is in safe mode due to power failure. Feed 5 units of Coal into the intake reactor to reboot systems.",
            "OPERATIVE TRANSMISSION\n\nEnter [BUILDING MODE] (Press Tab) to show your hotbar. Place your extraction Miner on the nearby Coal deposit, rotate it with [R], and route conveyors to the IDT intake."
        };
        DialogueType[] introTypes = new DialogueType[]
        {
            DialogueType.None,
            DialogueType.None,
            DialogueType.Announcer,
            DialogueType.Announcer
        };
        introDialogue = CreateDialogueSO(introTexts, introTypes);

        // 2. IDT Online & Store Locked Dialogue
        string[] onlineTexts = new string[]
        {
            "SYSTEM // INCOMING TRANSMISSION\n\nIntake registered: 5/5 Fuel units. IDT reactor boot complete. Satellite telemetry established. Account credited: +$100.",
            "OPERATIVE TRANSMISSION\n\nConnection restored. Excellent. However, the boot sequence energy signature has alerted local human security forces. Intrusion imminent.",
            "OPERATIVE TRANSMISSION\n\nRequisition catalog unlocked. Open the Store (Press E) immediately and purchase defensive ammunition or defensive structures to defend the ship."
        };
        DialogueType[] onlineTypes = new DialogueType[]
        {
            DialogueType.None,
            DialogueType.Announcer,
            DialogueType.Announcer
        };
        idtOnlineDialogue = CreateDialogueSO(onlineTexts, onlineTypes);

        // 3. Combat Raid Dialogue
        string[] combatTexts = new string[]
        {
            "OPERATIVE TRANSMISSION\n\nHostiles detected. Switch to [COMBAT MODE] (Press Tab) to arm your personal weapon. This locks building interfaces and enables Left Click aiming and shooting.",
            "OPERATIVE TRANSMISSION\n\nAim with Mouse, shoot with Left Click, and use Dodge-Roll (Space/Dodge key) to evade incoming fire. Do not let them breach the IDT. Eliminate them."
        };
        DialogueType[] combatTypes = new DialogueType[]
        {
            DialogueType.Announcer,
            DialogueType.Announcer
        };
        combatDialogue = CreateDialogueSO(combatTexts, combatTypes);
    }

    private DialogueSO CreateDialogueSO(string[] texts, DialogueType[] types)
    {
        DialogueSO so = ScriptableObject.CreateInstance<DialogueSO>();
        so.dialogues = new Dialogue[texts.Length];
        for (int i = 0; i < texts.Length; i++)
        {
            so.dialogues[i] = new Dialogue
            {
                text = texts[i],
                sprite = null,
                color = Color.clear,
                type = i < types.Length ? types[i] : DialogueType.None
            };
        }
        return so;
    }

    private void SubscribeEvents()
    {
        if (isSubscribed) return;
        isSubscribed = true;

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.OnDialogueEnded += HandleDialogueEnded;
            DialogueManager.Instance.CanAdvanceDialogue = CheckCanAdvanceDialogue;
        }

        PlayerWeapon.OnPlayerShoot += HandlePlayerShoot;
        
        if (PlayerController.Instance != null)
        {
            PlayerController.Instance.OnPlayerDodge += HandlePlayerDodge;
        }
    }

    private void UnsubscribeEvents()
    {
        if (!isSubscribed) return;
        isSubscribed = false;

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.OnDialogueEnded -= HandleDialogueEnded;
            DialogueManager.Instance.CanAdvanceDialogue = null;
        }

        PlayerWeapon.OnPlayerShoot -= HandlePlayerShoot;

        if (PlayerController.Instance != null)
        {
            PlayerController.Instance.OnPlayerDodge -= HandlePlayerDodge;
        }

        if (Seller.Instance != null)
        {
            Seller.Instance.OnFuelAdded -= HandleFuelAdded;
        }
    }

    protected override void OnDestroy()
    {
        base.OnDestroy();
        UnsubscribeEvents();
    }

    private IEnumerator StartTutorialRoutine()
    {
        yield return new WaitForSeconds(1.5f); // Let scene settle
        
        if (DayNightManager.Instance != null)
        {
            DayNightManager.Instance.isTutorialActive = true;
        }

        // Grant starting miner and conveyors
        GrantStartingItems();

        CreateObjectiveUI(); // Create the programmatic objective HUD
        currentState = TutorialState.CrashLandIntro;
        UpdateObjectiveText();
    }

    private void GrantStartingItems()
    {
        if (GameManager.Instance == null || GameManager.Instance.allBuildings == null) return;

        BuildingData minerData = null;
        BuildingData conveyorData = null;

        foreach (var b in GameManager.Instance.allBuildings)
        {
            if (b == null) continue;
            if (b.type == BuildingType.Miner) minerData = b;
            else if (b.type == BuildingType.Conveyor) conveyorData = b;
        }

        if (InventoryManager.Instance != null)
        {
            if (minerData != null) InventoryManager.Instance.AddBuilding(minerData, 1);
            if (conveyorData != null) InventoryManager.Instance.AddBuilding(conveyorData, 8);
        }
    }

    public bool IsStoreLocked()
    {
        return currentState == TutorialState.CrashLandIntro || currentState == TutorialState.PoweringUpIDT;
    }

    private void Update()
    {
        if (currentState == TutorialState.Completed) return;

        bool isStoreOpen = UiManager.Instance != null && UiManager.Instance.StorePanel != null && UiManager.Instance.StorePanel.activeSelf;

        // Core Tutorial State Transitions
        switch (currentState)
        {
            case TutorialState.CrashLandIntro:
                // Check if they toggled to Building mode
                if (PlayerController.Instance != null && PlayerController.Instance.currentMode == PlayerController.PlayerMode.Building)
                {
                    currentState = TutorialState.PoweringUpIDT;
                    UpdateObjectiveText();

                    // Subscribe to IDT fueling
                    if (Seller.Instance != null)
                    {
                        Seller.Instance.OnFuelAdded += HandleFuelAdded;
                    }

                    if (UiManager.HasInstance)
                    {
                        UiManager.Instance.ShowGeneralAlert("IDT OUT OF FUEL: COAL REQUIRED", new Color(1f, 0.5f, 0f));
                    }
                }
                break;

            case TutorialState.PoweringUpIDT:
                // Wait for fuel. Handled via HandleFuelAdded.
                // But we update objective text in case they mined coal manually
                UpdateObjectiveText();
                break;

            case TutorialState.IDTOnlineStoreLocked:
                // Wait for store to open
                if (isStoreOpen)
                {
                    currentState = TutorialState.RequisitionDefenses;
                    UpdateObjectiveText();
                }
                break;

            case TutorialState.RequisitionDefenses:
                // Wait until they buy ammo, wall, or turret AND close store
                bool hasBoughtDefense = GetInventoryCount(BuildingType.Turret) > 0 || 
                                       GetInventoryCount(BuildingType.Wall) > 0 || 
                                       (PlayerController.Instance != null && PlayerController.Instance.ammoReserve > 90);
                
                if (hasBoughtDefense && !isStoreOpen)
                {
                    currentState = TutorialState.CombatRaidInitiated;
                    UpdateObjectiveText();
                    
                    if (PlayerController.Instance != null)
                    {
                        PlayerController.Instance.canDodgeRoll = true; // Unlock dodge roll for tutorial
                    }

                    if (RaidManager.Instance != null)
                    {
                        RaidManager.Instance.StartCustomRaid(1, 2, 12f);
                    }
                }
                break;

            case TutorialState.CombatRaidInitiated:
                // Wait until they shot, dodge-rolled, and raid is repelled
                bool raidDefeated = RaidManager.Instance != null && !RaidManager.Instance.isRaidActive;
                int enemyCount = 0;
                if (GameManager.Instance != null && GameManager.Instance.ActiveEnemies != null)
                {
                    enemyCount = GameManager.Instance.ActiveEnemies.Count;
                }

                UpdateObjectiveText();

                if (hasFiredWeapon && hasDodgeRolled && raidDefeated && enemyCount == 0)
                {
                    currentState = TutorialState.Completed;
                    CompleteTutorial(true);
                }
                break;
        }
    }

    private void PlayDialogue(DialogueSO dialogue)
    {
        // Dialogue bypassed: we are using objective HUD instead
    }

    private bool CheckCanAdvanceDialogue()
    {
        return true;
    }

    private void AdvanceToDialogueIndex(int targetIndex)
    {
    }

    private void HandleDialogueEnded()
    {
    }

    private void HandleFuelAdded(ResourceType type)
    {
        if (currentState == TutorialState.PoweringUpIDT && type == ResourceType.Coal)
        {
            coalFedCount++;
            UpdateObjectiveText();
            
            if (coalFedCount >= 5)
            {
                if (Seller.Instance != null)
                {
                    Seller.Instance.OnFuelAdded -= HandleFuelAdded;
                }

                // Reboot IDT!
                currentState = TutorialState.IDTOnlineStoreLocked;
                UpdateObjectiveText();
                
                if (UiManager.HasInstance)
                {
                    UiManager.Instance.ShowGeneralAlert("IDT ONLINE - COMMUNICATIONS LINK ONLINE", new Color(0.2f, 1f, 0.2f));
                }

                if (CurrencyManager.Instance != null)
                {
                    CurrencyManager.Instance.AddCurrency(100f); // Startup grant
                }
            }
        }
    }

    private void HandlePlayerShoot()
    {
        if (currentState == TutorialState.CombatRaidInitiated)
        {
            hasFiredWeapon = true;
        }
    }

    private void HandlePlayerDodge()
    {
        if (currentState == TutorialState.CombatRaidInitiated)
        {
            hasDodgeRolled = true;
        }
    }

    private int GetInventoryCount(BuildingType type)
    {
        if (InventoryManager.Instance == null || InventoryManager.Instance.items == null) return 0;
        var item = InventoryManager.Instance.items.Find(i => i.data != null && i.data.type == type);
        return item != null ? item.count : 0;
    }

    public void CompleteTutorial(bool showVisual)
    {
        currentState = TutorialState.Completed;

        if (objectivePanel != null)
        {
            Destroy(objectivePanel);
        }

        if (showVisual)
        {
            ShowCompletionVisual();
        }

        PlayerPrefs.SetInt("PlayTutorial", 0);
        PlayerPrefs.Save();

        UnsubscribeEvents();

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.ToggleUi(false);
        }

        if (DayNightManager.Instance != null)
        {
            DayNightManager.Instance.CompleteTutorial();
            if (showVisual)
            {
                DayNightManager.Instance.timeRemaining = 10f; // Give them a few seconds before next day starts
            }
            else
            {
                DayNightManager.Instance.isTutorialActive = false;
            }
        }
    }

    public void RestartTutorial()
    {
        StopAllCoroutines();

        if (DialogueManager.Instance != null)
        {
            DialogueManager.Instance.ToggleUi(false);
        }

        currentState = TutorialState.CrashLandIntro;
        currentDialogueIndex = -1;
        coalFedCount = 0;
        hasFiredWeapon = false;
        hasDodgeRolled = false;
        // Reset states

        PlayerPrefs.SetInt("PlayTutorial", 1);
        PlayerPrefs.Save();

        if (DayNightManager.Instance != null)
        {
            DayNightManager.Instance.isTutorialActive = true;
        }

        SubscribeEvents();
        StartCoroutine(StartTutorialRoutine());
    }

    public static void RequestTutorialAgain()
    {
        PlayerPrefs.SetInt("PlayTutorial", 1);
        PlayerPrefs.Save();
        Debug.Log("Tutorial requested. It will play again on next scene start.");
    }

    private void ShowCompletionVisual()
    {
        GameObject canvasGo = GameObject.Find("HUD Canvas");
        if (canvasGo == null) canvasGo = GameObject.Find("Canvas");
        if (canvasGo == null) canvasGo = FindFirstObjectByType<Canvas>()?.gameObject;

        if (canvasGo == null) return;

        GameObject visualPanel = new GameObject("TutorialCompletionVisual", typeof(RectTransform), typeof(CanvasGroup));
        visualPanel.transform.SetParent(canvasGo.transform, false);

        RectTransform panelRt = visualPanel.GetComponent<RectTransform>();
        panelRt.anchorMin = new Vector2(0.5f, 0.5f);
        panelRt.anchorMax = new Vector2(0.5f, 0.5f);
        panelRt.pivot = new Vector2(0.5f, 0.5f);
        panelRt.anchoredPosition = new Vector2(0f, 100f);
        panelRt.sizeDelta = new Vector2(600f, 150f);

        CanvasGroup cg = visualPanel.GetComponent<CanvasGroup>();
        cg.alpha = 0f;

        GameObject bgGo = new GameObject("Background", typeof(RectTransform), typeof(Image));
        bgGo.transform.SetParent(visualPanel.transform, false);
        RectTransform bgRt = bgGo.GetComponent<RectTransform>();
        bgRt.anchorMin = Vector2.zero;
        bgRt.anchorMax = Vector2.one;
        bgRt.offsetMin = Vector2.zero;
        bgRt.offsetMax = Vector2.zero;
        Image bgImg = bgGo.GetComponent<Image>();
        bgImg.color = new Color(0f, 0.05f, 0f, 0.9f);
        Outline outline = bgGo.AddComponent<Outline>();
        outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.8f);
        outline.effectDistance = new Vector2(2f, -2f);

        GameObject textGo = new GameObject("Text", typeof(RectTransform), typeof(TextMeshProUGUI));
        textGo.transform.SetParent(visualPanel.transform, false);
        RectTransform textRt = textGo.GetComponent<RectTransform>();
        textRt.anchorMin = Vector2.zero;
        textRt.anchorMax = Vector2.one;
        textRt.offsetMin = new Vector2(10f, 10f);
        textRt.offsetMax = new Vector2(-10f, -10f);

        TextMeshProUGUI txt = textGo.GetComponent<TextMeshProUGUI>();
        txt.fontSize = 36;
        txt.fontStyle = FontStyles.Bold;
        txt.color = new Color(0.2f, 0.9f, 0.2f, 1f);
        txt.alignment = TextAlignmentOptions.Center;
        txt.text = "<color=#32FF32>TUTORIAL COMPLETED</color>\nSYSTEMS UNLOCKED\n<color=#FF3232>WARNING: RAID DETECTED</color>";

        Sequence seq = DOTween.Sequence();
        seq.Append(cg.DOFade(1f, 0.5f))
           .AppendInterval(0.2f)
           .AppendCallback(() => {
               outline.effectColor = new Color(1f, 0.2f, 0.2f, 0.9f);
           })
           .AppendInterval(0.3f)
           .AppendCallback(() => {
               outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.8f);
           })
           .AppendInterval(0.3f)
           .AppendCallback(() => {
               outline.effectColor = new Color(1f, 0.2f, 0.2f, 0.9f);
           })
           .AppendInterval(0.3f)
           .AppendCallback(() => {
               outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.8f);
           })
           .AppendInterval(2.5f)
           .Append(panelRt.DOAnchorPosY(150f, 0.8f).SetEase(Ease.InBack))
           .Join(cg.DOFade(0f, 0.8f))
           .AppendCallback(() => {
               Destroy(visualPanel);
           });

        seq.SetUpdate(true);
    }

    private void CreateObjectiveUI()
    {
        GameObject canvasGo = GameObject.Find("HUD Canvas");
        if (canvasGo == null) canvasGo = GameObject.Find("Canvas");
        if (canvasGo == null) canvasGo = FindFirstObjectByType<Canvas>()?.gameObject;

        if (canvasGo == null) return;

        objectivePanel = new GameObject("TutorialObjectivePanel", typeof(RectTransform), typeof(Image));
        objectivePanel.transform.SetParent(canvasGo.transform, false);

        RectTransform panelRt = objectivePanel.GetComponent<RectTransform>();
        panelRt.anchorMin = new Vector2(1f, 1f);
        panelRt.anchorMax = new Vector2(1f, 1f);
        panelRt.pivot = new Vector2(1f, 1f);
        panelRt.anchoredPosition = new Vector2(-20f, -80f);
        panelRt.sizeDelta = new Vector2(440f, 180f);

        Image img = objectivePanel.GetComponent<Image>();
        img.color = new Color(0.01f, 0.05f, 0.01f, 0.9f);

        Outline outline = objectivePanel.AddComponent<Outline>();
        outline.effectColor = new Color(0.2f, 0.9f, 0.2f, 0.7f);
        outline.effectDistance = new Vector2(2f, -2f);

        GameObject textGo = new GameObject("ObjectiveText", typeof(RectTransform), typeof(TextMeshProUGUI));
        textGo.transform.SetParent(objectivePanel.transform, false);

        RectTransform textRt = textGo.GetComponent<RectTransform>();
        textRt.anchorMin = Vector2.zero;
        textRt.anchorMax = Vector2.one;
        textRt.offsetMin = new Vector2(15f, 15f);
        textRt.offsetMax = new Vector2(-15f, -15f);

        objectiveText = textGo.GetComponent<TextMeshProUGUI>();
        objectiveText.fontSize = 26;
        objectiveText.color = new Color(0.2f, 1f, 0.2f);
        objectiveText.alignment = TextAlignmentOptions.TopLeft;
        objectiveText.enableWordWrapping = true;
        
        UpdateObjectiveText();
    }

    public void UpdateObjectiveText()
    {
        if (objectiveText == null) return;

        string title = "MISSION OBJECTIVES\n-----------------\n";
        string body = "";

        switch (currentState)
        {
            case TutorialState.CrashLandIntro:
                body = "- Press [TAB] to enter BUILDING MODE";
                break;
            case TutorialState.PoweringUpIDT:
                int coalInInventory = BuildingUiManager.Instance != null ? BuildingUiManager.Instance.GetResourceCount(ResourceType.Coal) : 0;
                
                if (coalFedCount == 0 && coalInInventory == 0)
                {
                    body = "- Mine Coal manually:\n  Hover Coal deposit & press [E]";
                }
                else
                {
                    body = $"- Build Miner on Coal deposit\n- Route conveyors to Reactor intake\n- Fuel Reactor (Coal fed: {coalFedCount}/5)";
                }
                break;
            case TutorialState.IDTOnlineStoreLocked:
                body = "- Access Ship Store Catalog (Press [E])";
                break;
            case TutorialState.RequisitionDefenses:
                body = "- Purchase defensive tech (Ammo, Turret, or Wall)\n- Close Shop to reboot shield";
                break;
            case TutorialState.CombatRaidInitiated:
                body = "- Press [TAB] to enter COMBAT MODE\n- Left-Click to shoot invaders\n- Space to Dodge-Roll\n- Defeat the landing force!";
                break;
            default:
                body = "Tutorial complete.";
                break;
        }

        objectiveText.text = title + body;
    }
}
